RegisterNetEvent('fl_core:anim:sync')
AddEventHandler('fl_core:anim:sync', function(target, animationLib,animationLib2, animation, animation2, distans, distans2, height,targetSrc,length,spin,controlFlagSrc,controlFlagTarget,animFlagTarget,attachFlag)
	TriggerClientEvent('fl_core:anim:syncTarget', targetSrc, source, animationLib2, animation2, distans, distans2, height, length,spin,controlFlagTarget,animFlagTarget,attachFlag)
	TriggerClientEvent('fl_core:anim:syncMe', source, animationLib, animation,length,controlFlagSrc,animFlagTarget)
end)

RegisterNetEvent('fl_core:anim:stop')
AddEventHandler('fl_core:anim:stop', function(targetSrc)
	TriggerClientEvent('fl_core:anim:cl_stop', targetSrc)
end)
