if not Config then Config = {} end
if _U == nil then function _U() end end

Config.Weapons = {

	{
		name = 'WEAPON_KNIFE',
		label = _U('weapon_knife'),
	},

	{
		name = 'WEAPON_NIGHTSTICK',
		label = _U('weapon_nightstick'),
	},

	{
		name = 'WEAPON_HAMMER',
		label = _U('weapon_hammer'),
	},

	{
		name = 'WEAPON_BAT',
		label = _U('weapon_bat'),
	},

	{
		name = 'WEAPON_katana',
		label = _U('weapon_katana'),
	},

	{
		name = 'WEAPON_GOLFCLUB',
		label = _U('weapon_golfclub'),
	},

	{
		name = 'WEAPON_CROWBAR',
		label = _U('weapon_crowbar'),
	},

	{
		name = 'WEAPON_PISTOL',
		label = _U('weapon_pistol'),
	},

	{
		name = 'WEAPON_PISTOL_MK2',
		label = _U('weapon_pistol_mk2'),
	},

	{
		name = 'WEAPON_COMBATPISTOL',
		label = _U('weapon_combatpistol'),
	},

	{
		name = 'WEAPON_APPISTOL',
		label = _U('weapon_appistol'),
	},

	{
		name = 'WEAPON_PISTOL50',
		label = _U('weapon_pistol50'),
	},

	{
		name = 'WEAPON_REVOLVER',
		label = _U('weapon_revolver'),
	},

	{
		name = 'WEAPON_REVOLVER_MK2',
		label = _U('weapon_revolver_mk2'),
	},

	{
		name = 'WEAPON_SNSPISTOL',
		label = _U('weapon_snspistol'),
	},

	{
		name = 'WEAPON_SNSPISTOL_MK2',
		label = _U('weapon_snspistol_mk2'),
	},

	{
		name = 'WEAPON_HEAVYPISTOL',
		label = _U('weapon_heavypistol'),
	},

	{
		name = 'WEAPON_VINTAGEPISTOL',
		label = _U('weapon_vintagepistol'),
	},

	{
		name = 'WEAPON_MICROSMG',
		label = _U('weapon_microsmg'),
	},

	{
		name = 'WEAPON_SMG',
		label = _U('weapon_smg'),
	},

	{
		name = 'WEAPON_SMG_MK2',
		label = _U('weapon_smg_mk2'),
	},

	{
		name = 'WEAPON_ASSAULTSMG',
		label = _U('weapon_assaultsmg'),
	},

	{
		name = 'WEAPON_MINISMG',
		label = _U('weapon_minismg'),
	},

	{
		name = 'WEAPON_MACHINEPISTOL',
		label = _U('weapon_machinepistol'),
	},

	{
		name = 'WEAPON_COMBATPDW',
		label = _U('weapon_combatpdw'),
	},

	{
		name = 'WEAPON_PUMPSHOTGUN',
		label = _U('weapon_pumpshotgun'),
	},

	{
		name = 'WEAPON_PUMPSHOTGUN_MK2',
		label = _U('weapon_pumpshotgun_mk2'),
	},

	{
		name = 'WEAPON_SAWNOFFSHOTGUN',
		label = _U('weapon_sawnoffshotgun'),
	},

	{
		name = 'WEAPON_ASSAULTSHOTGUN',
		label = _U('weapon_assaultshotgun'),
	},

	{
		name = 'WEAPON_BULLPUPSHOTGUN',
		label = _U('weapon_bullpupshotgun'),
	},

	{
		name = 'WEAPON_HEAVYSHOTGUN',
		label = _U('weapon_heavyshotgun'),
	},

	{
		name = 'WEAPON_ASSAULTRIFLE',
		label = _U('weapon_assaultrifle'),
	},

	{
		name = 'WEAPON_ASSAULTRIFLE_MK2',
		label = _U('weapon_assaultrifle_mk2'),
	},

	{
		name = 'WEAPON_CARBINERIFLE',
		label = _U('weapon_carbinerifle'),
	},

	{
		name = 'WEAPON_CARBINERIFLE_MK2',
		label = _U('weapon_carbinerifle_mk2'),
	},

	{
		name = 'WEAPON_ADVANCEDRIFLE',
		label = _U('weapon_advancedrifle'),
	},

	{
		name = 'WEAPON_SPECIALCARBINE',
		label = _U('weapon_specialcarbine'),
	},

	{
		name = 'WEAPON_SPECIALCARBINE_MK2',
		label = _U('weapon_specialcarbine_mk2'),
	},

	{
		name = 'WEAPON_BULLPUPRIFLE',
		label = _U('weapon_bullpuprifle'),
	},

	{
		name = 'WEAPON_BULLPUPRIFLE_MK2',
		label = _U('weapon_bullpuprifle_mk2'),
	},

	{
		name = 'WEAPON_COMPACTRIFLE',
		label = _U('weapon_compactrifle'),
	},

	{
		name = 'WEAPON_MG',
		label = _U('weapon_mg'),
	},

	{
		name = 'WEAPON_COMBATMG',
		label = _U('weapon_combatmg'),

	},

	{
		name = 'WEAPON_COMBATMG_MK2',
		label = _U('weapon_combatmg_mk2'),
	},

	{
		name = 'WEAPON_GUSENBERG',
		label = _U('weapon_gusenberg'),
	},

	{
		name = 'WEAPON_SNIPERRIFLE',
		label = _U('weapon_sniperrifle'),
	},

	{
		name = 'WEAPON_HEAVYSNIPER',
		label = _U('weapon_heavysniper'),
	},

	{
		name = 'WEAPON_HEAVYSNIPER_MK2',
		label = _U('weapon_heavysniper_mk2'),
	},

	{
		name = 'WEAPON_MARKSMANRIFLE',
		label = _U('weapon_marksmanrifle'),
	},

	{
		name = 'WEAPON_MARKSMANRIFLE_MK2',
		label = _U('weapon_marksmanrifle_mk2'),
	},

	{
		name = 'WEAPON_GRENADELAUNCHER',
		label = _U('weapon_grenadelauncher'),
	},

	{
		name = 'WEAPON_GRENADELAUNCHER_SMOKE',
		label = _U('weapon_grenadelauncher_smoke'),
	},

	{
		name = 'WEAPON_RPG',
		label = _U('weapon_rpg'),
	},

	{
		name = 'WEAPON_STINGER',
		label = _U('weapon_stinger'),
	},

	{
		name = 'WEAPON_MINIGUN',
		label = _U('weapon_minigun'),
	},

	{
		name = 'WEAPON_GRENADE',
		label = _U('weapon_grenade'),
	},

	{
		name = 'WEAPON_STICKYBOMB',
		label = _U('weapon_stickybomb'),
	},

	{
		name = 'WEAPON_SMOKEGRENADE',
		label = _U('weapon_smokegrenade'),
	},

	{
		name = 'WEAPON_BZGAS',
		label = _U('weapon_bzgas'),
	},

	{
		name = 'WEAPON_MOLOTOV',
		label = _U('weapon_molotov'),
	},

	{
		name = 'WEAPON_FIREEXTINGUISHER',
		label = _U('weapon_fireextinguisher'),
	},

	{
		name = 'WEAPON_PETROLCAN',
		label = _U('weapon_petrolcan'),
	},

	{
		name = 'WEAPON_DIGISCANNER',
		label = _U('weapon_digiscanner'),
	},

	{
		name = 'WEAPON_BALL',
		label = _U('weapon_ball'),
	},

	{
		name = 'WEAPON_BOTTLE',
		label = _U('weapon_bottle'),
	},

	{
		name = 'WEAPON_DAGGER',
		label = _U('weapon_dagger'),
	},

	{
		name = 'WEAPON_FIREWORK',
		label = _U('weapon_firework'),
	},

	{
		name = 'WEAPON_MUSKET',
		label = _U('weapon_musket'),
	},

	{
		name = 'WEAPON_STUNGUN',
		label = _U('weapon_stungun'),
	},

	{
		name = 'WEAPON_HOMINGLAUNCHER',
		label = _U('weapon_hominglauncher'),
	},

	{
		name = 'WEAPON_PROXMINE',
		label = _U('weapon_proxmine'),
	},

	{
		name = 'WEAPON_SNOWBALL',
		label = _U('weapon_snowball'),
	},

	{
		name = 'WEAPON_FLAREGUN',
		label = _U('weapon_flaregun'),
	},

	{
		name = 'WEAPON_GARBAGEBAG',
		label = _U('weapon_garbagebag'),
	},

	{
		name = 'WEAPON_HANDCUFFS',
		label = _U('weapon_handcuffs'),
	},

	{
		name = 'WEAPON_MARKSMANPISTOL',
		label = _U('weapon_marksmanpistol'),
	},

	{
		name = 'WEAPON_KNUCKLE',
		label = _U('weapon_knuckle'),
	},

	{
		name = 'WEAPON_HATCHET',
		label = _U('weapon_hatchet'),
	},

	{
		name = 'WEAPON_RAILGUN',
		label = _U('weapon_railgun'),
	},

	{
		name = 'WEAPON_MACHETE',
		label = _U('weapon_machete'),
	},

	{
		name = 'WEAPON_SWITCHBLADE',
		label = _U('weapon_switchblade'),
	},

	{
		name = 'WEAPON_DBSHOTGUN',
		label = _U('weapon_dbshotgun'),
	},

	{
		name = 'WEAPON_AUTOSHOTGUN',
		label = _U('weapon_autoshotgun'),
	},

	{
		name = 'WEAPON_BATTLEAXE',
		label = _U('weapon_battleaxe'),
	},

	{
		name = 'WEAPON_COMPACTLAUNCHER',
		label = _U('weapon_compactlauncher'),
	},

	{
		name = 'WEAPON_PIPEBOMB',
		label = _U('weapon_pipebomb'),
	},

	{
		name = 'WEAPON_POOLCUE',
		label = _U('weapon_poolcue'),
	},

	{
		name = 'WEAPON_WRENCH',
		label = _U('weapon_wrench'),
	},

	{
		name = 'WEAPON_FLASHLIGHT',
		label = _U('weapon_flashlight'),
	},

	{
		name = 'GADGET_NIGHTVISION',
		label = _U('gadget_nightvision'),
	},

	{
		name = 'GADGET_PARACHUTE',
		label = _U('gadget_parachute'),
	},

	{
		name = 'WEAPON_FLARE',
		label = _U('weapon_flare'),
	},

	{
		name = 'WEAPON_DOUBLEACTION',
		label = _U('weapon_doubleaction'),
	},

	{
		name = 'WEAPON_RAYPISTOL',
		label = _U('weapon_raypistol'),
	},

	{
		name = 'WEAPON_RAYCARBINE',
		label = _U('weapon_raycarbine'),
	},

	{
		name = 'WEAPON_RAYMINIGUN',
		label = _U('weapon_rayminigun'),
	},

	{
		name = 'WEAPON_STONE_HATCHET',
		label = _U('weapon_stone_hatchet'),
	},

	{
		name = 'WEAPON_CERAMICPISTOL',
		label = 'Pistolet céramique',
	},

	{
		name = 'WEAPON_NAVYREVOLVER',
		label = 'Navy Revolver',
	},

	{
		name = 'WEAPON_COMBATSHOTGUN',
		label = 'SPAS 12',
	},

	{
		name = 'WEAPON_GADGETPISTOL',
		label = 'Pistolet Perico',
	},

	{
		name = 'WEAPON_MILITARYRIFLE',
		label = 'Steyr AUG',
	},

}

Config.Components = {
	["COMPONENT_ADVANCEDRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_ADVANCEDRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"] = 'WCT_VAR_METAL',
	["COMPONENT_APPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_APPISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_APPISTOL_VARMOD_LUXE"] = 'WCT_VAR_METAL',
	["COMPONENT_ASSAULTRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_ASSAULTRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_ASSAULTRIFLE_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_ASSAULTRIFLE_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_ASSAULTSHOTGUN_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_ASSAULTSHOTGUN_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_ASSAULTSMG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_ASSAULTSMG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"] = 'WCT_VAR_GOLD',
	["COMPONENT_AT_AR_AFGRIP_02"] = 'WCT_GRIP',
	["COMPONENT_AT_AR_AFGRIP"] = 'WCT_GRIP',
	["COMPONENT_AT_AR_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_AR_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_AR_FLSH"] = 'WCT_FLASH',
	["COMPONENT_AT_AR_SUPP_02"] = 'WCT_SUPP',
	["COMPONENT_AT_AR_SUPP"] = 'WCT_SUPP',
	["COMPONENT_AT_BP_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_BP_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_CR_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_CR_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_MG_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_MG_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_MRFL_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_MRFL_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_MUZZLE_01"] = 'WCT_MUZZ1',
	["COMPONENT_AT_MUZZLE_02"] = 'WCT_MUZZ2',
	["COMPONENT_AT_MUZZLE_03"] = 'WCT_MUZZ3',
	["COMPONENT_AT_MUZZLE_04"] = 'WCT_MUZZ4',
	["COMPONENT_AT_MUZZLE_05"] = 'WCT_MUZZ5',
	["COMPONENT_AT_MUZZLE_06"] = 'WCT_MUZZ6',
	["COMPONENT_AT_MUZZLE_07"] = 'WCT_MUZZ7',
	["COMPONENT_AT_MUZZLE_08"] = 'WCT_MUZZ',
	["COMPONENT_AT_MUZZLE_09"] = 'WCT_MUZZ9',
	["COMPONENT_AT_PI_COMP_02"] = 'WCT_COMP',
	["COMPONENT_AT_PI_COMP_03"] = 'WCT_COMP',
	["COMPONENT_AT_PI_COMP"] = 'WCT_COMP',
	["COMPONENT_AT_PI_FLSH_02"] = 'WCT_FLASH',
	["COMPONENT_AT_PI_FLSH_03"] = 'WCT_FLASH',
	["COMPONENT_AT_PI_FLSH"] = 'WCT_FLASH',
	["COMPONENT_AT_PI_RAIL_02"] = 'WCT_SCOPE_PI',
	["COMPONENT_AT_PI_RAIL"] = 'WCT_SCOPE_PI',
	["COMPONENT_AT_PI_SUPP_02"] = 'WCT_SUPP',
	["COMPONENT_AT_PI_SUPP"] = 'WCT_SUPP',
	["COMPONENT_AT_SB_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_SB_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_SC_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_SC_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"] = 'WCT_SCOPE_LRG2',
	["COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"] = 'WCT_SCOPE_LRG',
	["COMPONENT_AT_SCOPE_LARGE_MK2"] = 'WCT_SCOPE_LRG2',
	["COMPONENT_AT_SCOPE_LARGE"] = 'WCT_SCOPE_LRG',
	["COMPONENT_AT_SCOPE_MACRO_02_MK2"] = 'WCT_SCOPE_MAC2',
	["COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"] = 'WCT_SCOPE_MAC2',
	["COMPONENT_AT_SCOPE_MACRO_02"] = 'WCT_SCOPE_MAC',
	["COMPONENT_AT_SCOPE_MACRO_MK2"] = 'WCT_SCOPE_MAC2',
	["COMPONENT_AT_SCOPE_MACRO"] = 'WCT_SCOPE_MAC',
	["COMPONENT_AT_SCOPE_MAX"] = 'WCT_SCOPE_MAX',
	["COMPONENT_AT_SCOPE_MEDIUM_MK2"] = 'WCT_SCOPE_MED2',
	["COMPONENT_AT_SCOPE_MEDIUM"] = 'WCT_SCOPE_LRG',
	["COMPONENT_AT_SCOPE_NV"] = 'WCT_SCOPE_NV',
	["COMPONENT_AT_SCOPE_SMALL_02"] = 'WCT_SCOPE_SML',
	["COMPONENT_AT_SCOPE_SMALL_MK2"] = 'WCT_SCOPE_SML2',
	["COMPONENT_AT_SCOPE_SMALL_SMG_MK2"] = 'WCT_SCOPE_SML2',
	["COMPONENT_AT_SCOPE_SMALL"] = 'WCT_SCOPE_SML',
	["COMPONENT_AT_SCOPE_THERMAL"] = 'WCT_SCOPE_TH',
	["COMPONENT_AT_SIGHTS_SMG"] = 'WCT_HOLO',
	["COMPONENT_AT_SIGHTS"] = 'WCT_HOLO',
	["COMPONENT_AT_SR_BARREL_01"] = 'WCT_BARR',
	["COMPONENT_AT_SR_BARREL_02"] = 'WCT_BARR2',
	["COMPONENT_AT_SR_SUPP_03"] = 'WCT_SUPP',
	["COMPONENT_AT_SR_SUPP"] = 'WCT_SUPP',
	["COMPONENT_BULLPUPRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_BULLPUPRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_BULLPUPRIFLE_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_BULLPUPRIFLE_VARMOD_LOW"] = 'WCT_VAR_METAL',
	["COMPONENT_CARBINERIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_CARBINERIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_CARBINERIFLE_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_CARBINERIFLE_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_CARBINERIFLE_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_COMBATMG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_COMBATMG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_COMBATMG_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_COMBATMG_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_COMBATMG_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_COMBATMG_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_COMBATMG_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_COMBATMG_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_COMBATMG_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_COMBATMG_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_COMBATMG_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_COMBATMG_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_COMBATMG_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_COMBATMG_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_COMBATMG_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_COMBATMG_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_COMBATMG_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_COMBATPDW_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_COMBATPDW_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_COMBATPDW_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_COMBATPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_COMBATPISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"] = 'WCT_VAR_GOLD',
	["COMPONENT_COMPACTRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_COMPACTRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_COMPACTRIFLE_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_GUSENBERG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_GUSENBERG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_HEAVYPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_HEAVYPISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_HEAVYPISTOL_VARMOD_LUXE"] = 'WCT_VAR_WOOD',
	["COMPONENT_HEAVYSHOTGUN_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_HEAVYSHOTGUN_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_HEAVYSHOTGUN_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_HEAVYSNIPER_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"] = 'WCT_CLIP_EX',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_KNUCKLE_VARMOD_BALLAS"] = 'WCT_KNUCK_BG',
	["COMPONENT_KNUCKLE_VARMOD_BASE"] = 'WCT_KNUCK_01',
	["COMPONENT_KNUCKLE_VARMOD_DIAMOND"] = 'WCT_KNUCK_DMD',
	["COMPONENT_KNUCKLE_VARMOD_DOLLAR"] = 'WCT_KNUCK_DLR',
	["COMPONENT_KNUCKLE_VARMOD_HATE"] = 'WCT_KNUCK_HT',
	["COMPONENT_KNUCKLE_VARMOD_KING"] = 'WCT_KNUCK_SLG',
	["COMPONENT_KNUCKLE_VARMOD_LOVE"] = 'WCT_KNUCK_LV',
	["COMPONENT_KNUCKLE_VARMOD_PIMP"] = 'WCT_KNUCK_02',
	["COMPONENT_KNUCKLE_VARMOD_PLAYER"] = 'WCT_KNUCK_PC',
	["COMPONENT_KNUCKLE_VARMOD_VAGOS"] = 'WCT_KNUCK_VG',
	["COMPONENT_MACHINEPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MACHINEPISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MACHINEPISTOL_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_MARKSMANRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MARKSMANRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"] = 'WCT_CAMO_10',
	["COMPONENT_MARKSMANRIFLE_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_MG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MG_VARMOD_LOWRIDER"] = 'WCT_VAR_GOLD',
	["COMPONENT_MICROSMG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MICROSMG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MICROSMG_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_MINISMG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MINISMG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_PISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_PISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_PISTOL_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_PISTOL_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_PISTOL_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_PISTOL_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_PISTOL_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_PISTOL_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_PISTOL_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_PISTOL_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_PISTOL_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_PISTOL_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_PISTOL_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_PISTOL_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_PISTOL_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_PISTOL_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"] = 'WCT_CLIP_HP',
	["COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_PISTOL_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_PISTOL_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_PISTOL50_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_PISTOL50_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_PISTOL50_VARMOD_LUXE"] = 'WCT_VAR_SIL',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_PUMPSHOTGUN_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"] = 'WCT_SHELL',
	["COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"] = 'WCT_SHELL_AP',
	["COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"] = 'WCT_SHELL_EX',
	["COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"] = 'WCT_SHELL_HP',
	["COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"] = 'WCT_SHELL_INC',
	["COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"] = 'WCT_VAR_GOLD',
	["COMPONENT_REVOLVER_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_REVOLVER_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_REVOLVER_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_REVOLVER_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_REVOLVER_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_REVOLVER_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_REVOLVER_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_REVOLVER_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_REVOLVER_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_REVOLVER_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_REVOLVER_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_REVOLVER_MK2_CLIP_01"] = 'WCT_CLIP1_RV',
	["COMPONENT_REVOLVER_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"] = 'WCT_CLIP_HP',
	["COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_REVOLVER_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_REVOLVER_VARMOD_BOSS"] = 'WCT_REV_VARB',
	["COMPONENT_REVOLVER_VARMOD_GOON"] = 'WCT_REV_VARG',
	["COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"] = 'WCT_VAR_METAL',
	["COMPONENT_SMG_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SMG_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SMG_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_SMG_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_SMG_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_SMG_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_SMG_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_SMG_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_SMG_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_SMG_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_SMG_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_SMG_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_SMG_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_SMG_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_SMG_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SMG_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SMG_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"] = 'WCT_CLIP_HP',
	["COMPONENT_SMG_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_SMG_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_SMG_VARMOD_LUXE"] = 'WCT_VAR_GOLD',
	["COMPONENT_SNIPERRIFLE_VARMOD_LUXE"] = 'WCT_VAR_WOOD',
	["COMPONENT_SNSPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SNSPISTOL_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SNSPISTOL_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_SNSPISTOL_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_SNSPISTOL_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_SNSPISTOL_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_SNSPISTOL_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_SNSPISTOL_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_SNSPISTOL_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_SNSPISTOL_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_SNSPISTOL_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"] = 'WCT_CAMO_10',
	["COMPONENT_SNSPISTOL_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_SNSPISTOL_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SNSPISTOL_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"] = 'WCT_CLIP_HP',
	["COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"] = 'WCT_VAR_WOOD',
	["COMPONENT_SPECIALCARBINE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SPECIALCARBINE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SPECIALCARBINE_CLIP_03"] = 'WCT_CLIP_DRM',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_02"] = 'WCT_CAMO_2',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_03"] = 'WCT_CAMO_3',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_04"] = 'WCT_CAMO_4',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_05"] = 'WCT_CAMO_5',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_06"] = 'WCT_CAMO_6',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_07"] = 'WCT_CAMO_7',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_08"] = 'WCT_CAMO_8',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_09"] = 'WCT_CAMO_9',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_10"] = 'WCT_CAMO_10',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"] = 'WCT_CAMO_IND',
	["COMPONENT_SPECIALCARBINE_MK2_CAMO"] = 'WCT_CAMO_1',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"] = 'WCT_CLIP_AP',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"] = 'WCT_CLIP_FMJ',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"] = 'WCT_CLIP_INC',
	["COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"] = 'WCT_CLIP_TR',
	["COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"] = 'WCT_VAR_ETCHM',
	["COMPONENT_SWITCHBLADE_VARMOD_BASE"] = 'WCT_SB_BASE',
	["COMPONENT_SWITCHBLADE_VARMOD_VAR1"] = 'WCT_SB_VAR1',
	["COMPONENT_SWITCHBLADE_VARMOD_VAR2"] = 'WCT_SB_VAR2',
	["COMPONENT_VINTAGEPISTOL_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_VINTAGEPISTOL_CLIP_02"] = 'WCT_CLIP2',
	-- CHRISTMAS 2018 DLC (v 1604)
	["COMPONENT_RAYPISTOL_VARMOD_XMAS18"] = 'WCT_VAR_RAY18',
	-- DLC Cayo Perico heist4
	["COMPONENT_MILITARYRIFLE_CLIP_01"] = 'WCT_CLIP1',
	["COMPONENT_MILITARYRIFLE_CLIP_02"] = 'WCT_CLIP2',
	["COMPONENT_MILITARYRIFLE_SIGHT_01"] = 'WCT_MRFL_SIGHT',
}

for _,Weapon in pairs(Config.Weapons) do
	Weapon.item = string.lower(Weapon.name:gsub('WEAPON_', ''))
	Weapon.hash = GetHashKey(Weapon.name)

	if not IsDuplicityVersion() then
		Weapon.componentsList = {}
		for Component,ComponentType in pairs(Config.Components) do
			if DoesWeaponTakeWeaponComponent(Weapon.hash, Component) then
				table.insert(Weapon.componentsList, Component)
			end
		end
	end
end

