Citizen.CreateThread(function()
    local interiorId = GetInteriorAtCoords(1550.0, 250.0, -48.0)
    ActivateInteriorEntitySet(interiorId, 'EntitySet_DJ_Lighting')
    EnableInteriorProp(interiorId, 'dj_01_lights_02')
    EnableInteriorProp(interiorId, 'dj_01_lights_03')
    EnableInteriorProp(interiorId, 'dj_01_lights_04')
    EnableInteriorProp(interiorId, 'dj_02_lights_01')
    EnableInteriorProp(interiorId, 'dj_02_lights_02')
    EnableInteriorProp(interiorId, 'dj_02_lights_03')
    EnableInteriorProp(interiorId, 'dj_02_lights_04')
    EnableInteriorProp(interiorId, 'dj_03_lights_01')
    EnableInteriorProp(interiorId, 'dj_03_lights_02')
    EnableInteriorProp(interiorId, 'dj_03_lights_03')
    EnableInteriorProp(interiorId, 'dj_03_lights_04')
    EnableInteriorProp(interiorId, 'dj_04_lights_01')
    EnableInteriorProp(interiorId, 'dj_04_lights_02')
    EnableInteriorProp(interiorId, 'dj_04_lights_03')
    EnableInteriorProp(interiorId, 'dj_04_lights_04')
    EnableInteriorProp(interiorId, 'int01_ba_bar_content')
    EnableInteriorProp(interiorId, 'int01_ba_booze_01')
    EnableInteriorProp(interiorId, 'int01_ba_booze_02')
    EnableInteriorProp(interiorId, 'int01_ba_booze_03')
    EnableInteriorProp(interiorId, 'int01_ba_dj01')
    EnableInteriorProp(interiorId, 'int01_ba_dj02')
    EnableInteriorProp(interiorId, 'int01_ba_dj03')
    EnableInteriorProp(interiorId, 'int01_ba_dj04')
    EnableInteriorProp(interiorId, 'int01_ba_dj_keinemusik')
    EnableInteriorProp(interiorId, 'int01_ba_dj_moodyman')
    EnableInteriorProp(interiorId, 'int01_ba_dj_palms_trax')
    EnableInteriorProp(interiorId, 'int01_ba_dry_ice')
    EnableInteriorProp(interiorId, 'int01_ba_equipment_setup')
    EnableInteriorProp(interiorId, 'int01_ba_equipment_upgrade')
    EnableInteriorProp(interiorId, 'int01_ba_lightgrid_01')
    EnableInteriorProp(interiorId, 'int01_ba_lights_screen')
    EnableInteriorProp(interiorId, 'int01_ba_screen')
    EnableInteriorProp(interiorId, 'int01_ba_security_upgrade')
    EnableInteriorProp(interiorId, 'int01_ba_style02_podium')
    DisableInteriorProp(interiorId, 'light_rigs_off')
    RefreshInterior(interiorId)
end)